### ISSUE TITLE
Slight CSS issue on Firefox on the search

### ISSUE THREAD

**Issue by OverByThere** [mikebell/mikebell.io#3]
It seems the padding may be incorrect for Firefox for the search, see attached image (on OS X):
![Image of fault on FF](http://i.imgur.com/Nk4PXAx.png)

**Comment by mikebell** [comment]
Ah that's still running on Ghost, I'm in the process of converting to Sculpin (which is what this repo is).

I think I'm going to remove the search from the site anyway.
